crc lib plus 0x83 poly for ota crc
AlessandroAU/ExpressLRS pull request #210
Opened 2020-11-09 15:00 UTC by AlessandroAU

2020-11-09 22:02 UTC, cruwaller requested changes

2020-11-09 22:02 UTC, cruwaller commented on src/lib/CRC/crc.cpp
> +#include "crc.h"
Generic. Please harmonize datatypes and use either main types or fixed width type (recommended).

2020-11-10 02:03 UTC, AlessandroAU commented on src/src/rx_main.cpp
> +GENERIC_CRC8 ota_crc(ELRS_CRC_POLY);
Elrs crc and crsf crc are going to use different poly after this merge so I don't think this is possible as the precomputed tables will differ.

2020-11-10 05:27 UTC, cruwaller commented on src/src/rx_main.cpp
> +GENERIC_CRC8 ota_crc(ELRS_CRC_POLY);
I that case you need two.
Please, introduce 2 defines and comment. Then it is easier to follow.

2020-11-10 06:00 UTC, AlessandroAU commented on src/src/rx_main.cpp
> +GENERIC_CRC8 ota_crc(ELRS_CRC_POLY);
I put the defines in common, you think better in rx_main/tx_main?

2020-11-10 06:08 UTC, cruwaller commented on src/src/rx_main.cpp
> +GENERIC_CRC8 ota_crc(ELRS_CRC_POLY);
I think common is ok for RX/TX. I would put CRSF into CRSF.h and rename it to CRSF specific :)

2020-11-15 12:41 UTC, AlessandroAU commented
no this is something else. @cruwaller happy to merge?

2020-11-15 15:19 UTC, cruwaller approved these changes
This PR is hard to follow because all master-dev commits are shown as a changes. Proper rebase need to be used in future PRs...

2020-11-16 06:37 UTC, merged