Ghost tx
AlessandroAU/ExpressLRS pull request #327
Opened 2021-01-25 03:36 UTC by atr2600

It compiles!!!

Things we need to check!
- [ ] Pin logic, are we setting the amp high and the antennas correctly
- [ ] Variants, really having a hard time grasping at that Arduino structure. 
- [ ] Check `crsf.cpp` I needed to include a define statement there. 
- [ ] other stuff most likely!

BUT it compiles :)

2021-01-31 14:59 UTC, brandonrc commented
Update: We are binding to TX and communicating with OpenTX

2021-02-04 14:11 UTC, brandonrc commented
Going to do some testing at the field Saturday :)

2021-02-12 22:55 UTC, brandonrc commented
@hydra I agree about the comment, I think it was pulled in during a commit with  @AlessandroAU . I am not sure. I would like to remove anything that is not related to GHOST_TX out of this PR.

2021-02-14 19:32 UTC, cruwaller requested changes
FIY, should be rebased to `develop` (if not done yet).

2021-02-14 19:32 UTC, cruwaller commented on src/boards/GHOST_TX.json
> +  "url": "https://github.com/TauLabs/TauLabs/wiki/Sparky",
url = https://www.immersionrc.com/fpv-products/ghost/
vendor = ImmersionRC

2021-02-14 19:32 UTC, cruwaller commented on src/lib/CRSF/CRSF.cpp
> +                    CRSF::Port.begin(CRSF_OPENTX_FAST_BAUDRATE);
these 3 lines are duplicate to above.

2021-02-14 19:32 UTC, cruwaller commented on src/lib/SX1280Driver/SX1280_hal.cpp
> +  digitalWrite(GPIO_PIN_ANT_CTRL_1, HIGH);
Indention
(same below)

2021-02-14 19:32 UTC, cruwaller commented on src/platformio.ini
> +monitor_speed = 200000
why this is changed?

2021-02-14 19:32 UTC, cruwaller commented on src/platformio.ini
> +	https://github.com/PaoloP74/extEEPROM.git
This is not needed with latest `develop` changes.

2021-02-14 19:32 UTC, cruwaller commented on src/variants/GHOST_ATTO/variant.h
> +#define PA10 0    //
These comments does not belongs to here. These variant names (mcu type specific) should be changed to more generic in the future to avoid copy code.

2021-02-17 01:00 UTC, brandonrc commented on src/platformio.ini
> +monitor_speed = 200000
Good question.. let me fix that

2021-02-17 01:02 UTC, AlessandroAU commented on src/lib/CRSF/CRSF.cpp
> +                    CRSF::Port.begin(CRSF_OPENTX_FAST_BAUDRATE);
my fault

2021-02-17 01:35 UTC, brandonrc commented
@AlessandroAU if you could check the power levels for 

- [ ] 10mW
- [ ] 25mW
- [ ] 50mW
- [ ] 100mW 
- [ ] 250mW

2021-02-17 06:48 UTC, cruwaller approved these changes
Thanks! Lgtm 👍

2021-02-17 14:04 UTC, AlessandroAU commented
Power checked and all working. Still need bootloader but LGTM for now :)

2021-02-17 14:04 UTC, merged